Patch from `osx` to build ICL on mac
iclcv/icl pull request #6
Opened 2017-10-16 09:18 UTC by aleneum

This makes CMAKE more flexible and allows to also build `dylib` for OSX builts.
Additionally, there is a script which can be used to test homebrew builds locally first.

2017-10-16 10:15 UTC, scires approved these changes

2017-10-16 10:54 UTC, rhaschke requested changes
Looks fine so far. I would integrate `scripts/icl-homebrew-test.sh` into `.travis.yaml`.

2017-10-16 20:53 UTC, celbrech commented
looks good to me, well done!

2017-10-17 11:55 UTC, rhaschke requested changes
.travis.yml should be finally extended with osx stuff.

2017-10-17 11:55 UTC, rhaschke commented on .travis.yml
> +      script: sh scripts/icl-homebrew-test.sh
Actually, I meant to not simply _call_ the script from Travis, but to _get rid of_ the script and use the [Travis' way to install osx dependencies](https://docs.travis-ci.com/user/reference/osx) and finally build as usual.

2017-10-18 15:58 UTC, aleneum commented
closing this for now until osx job runs stable

2017-10-18 15:58 UTC, closed without merging